### PR TITLE
Enable Nullable Reference Type(only warnings)

### PR DESCRIPTION
**Pull request by nogic1008**
## Nullable Reference Type
- set `LangVersion` to `8.0`
  - not to `latest` because C# 7.x Compiler interprets it as `7.x`.
- set `Nullable` to `warnings`
- fix warnings caused by NRT
  - CS8600: Converting null literal or possible null value to non-nullable type.
  - CS8602: Dereference of a possibly null reference.

Nullable annotations are not set because of breaking change for programs used this library.
## Other Fixes
- ~~accept some suggested code by IDE (excludes [/sandbox](https://github.com/Cysharp/MicroBatchFramework/tree/master/sandbox) folder)~~
- remove and sort `using` directive
- ~~add scope `private` explicitly~~

### CODE REVIEW

**Comment by neuecc** [comment]
Thanks!
I want to accept it.
But IDE**** fix is not needed.

**Comment by nogic1008** [comment]
Okay, I'll reverted it.

**Comment by nogic1008** [comment]
And, do you think to need Nullable annotations?
I can help you add them.

**Comment by neuecc** [comment]
thanks, merge it.
Annotation, I will think later.

**Pull request merged**
