### PR TITLE
feat: Add MicroBatchHost as a Default Builder

### PR DESCRIPTION
**Pull request by guitarrapc**
## TL;DR;

Offer default builder as asp.net core webhost does.
This will make user don't need to think about configuration.

## Question 
Should Replace other samples to use MicroBatchHost?

## TODO

- [x] add default builder with SimpleLogger
- [x] refactor Configuration Sample
- [ ] add README section for MicroBatchHost
- [ ] fix README for Configuration Sample

### CODE REVIEW

**Comment by neuecc** [comment]
namespace should change to another one.
because if microsoft provides official `CreateDefaultBuilder`, will be conflict.
`MicroBatchFramework` -> `MicroBatchFramework.Configuration` ?

**Comment by guitarrapc** [comment]
- [ ] Change namespace
- [ ] Pass Logging Level to Simple Logger

**Comment by guitarrapc** [comment]
* Added `logging.AddFilter<SimpleConsoleLoggerProvider>($"MicroBatchFramework.{nameof(BatchEngine)}", minLogLevel);` to control SimpleConsoleLogger's loglevel.
* Introduce new argument with LogLevel `MicroBatchHost.CreateDefaultBuilder(args, LogLevel)`.

### MEMO:

From my investigation, ASP.NET Core Webhost and GenricHost provide 2 option to change Default Logging Level.

* [`ILoggingBuilder.SetMinimumLevel(LogLevel)`](https://github.com/aspnet/Extensions/blob/f162f1006bf8954f0102af8ff98c04077cf21b04/src/Logging/Logging/src/LoggingBuilderExtensions.cs): This change ILogger default level so the effect is not only `SimpleConsoleLogger`.
* [`ILoggingBuilder.AddFilter<T>("section(FullNameToTheClass)", LogLevel)`](https://github.com/aspnet/Extensions/blob/f162f1006bf8954f0102af8ff98c04077cf21b04/src/Logging/Logging/src/FilterLoggingBuilderExtensions.cs): This only effect to the T logger and section.

The other solution is create ILogger<SimpleConsoleLogger> from LoggerFactory but I think it's worst case.

I think it's better use `AddFilter<T>` for the library usecase. So that user can change their preference as they want.

**Comment by neuecc** [comment]
thank you! great improvment.

**Comment by guitarrapc** [comment]
thx, I will send new pr to update README.

**Pull request merged**
